[common]
ckb_uri = "http://localhost:8114"
ckb_indexer_uri = "http://localhost:8116"
composer_privkey = "8d929e962f940f75aa32054f19a5ea2ce70ae30bfe4ff7cf2dbed70d556265df" # pubkey_hash = "58b85c196e5fe80e25b4dab596e7121d219f79fb"
user_privkey = "d44955b4770247b233c284268c961085e622febb61d364c9a5cabe0c238f08d4" # pubkey_hash = "40e88263ef526a8248570e931cfb2f2fb3ed044f"

[nft]
tx_hash = "41a632a4e101ad47a6271f07b11d2f0e9fad334881dac4078aae48d54ef937b8"
code_hash = "b79c9e435742b9c939439303b279afdc3f92b377be7a187f4e690fd726141553"

[wallet]
tx_hash = "f302ff2f4f9cbc89f0e5e44958203912ef2907afde3697acfb3133d3552da538"
code_hash = "89eab80e842d6937ea5b266828284ab67d4c9a1b66651c5c6ece397bc6c47d0e"

[payment]
tx_hash = "eb586636680ea002f77058f01fdf0143d0f6675c25a624462f94688cd07d7e5c"
code_hash = "80d351c92602c4ad201d0cad2645ea02c45a026c7d70d92f79399dfaf8540ff4"

[kabletop]
tx_hash = "d8dc4ba26b4a6c6ae0f6b8eba4d79c25892cc7a0bd7a5a5af2431876d6c476cf"
code_hash = "fc83d7e9a86228c1b9c2062c2d679a60b5116b4bb3223f5e857100f46e221177"
